```{r}
setwd('C:/Users/anafe/OneDrive/Área de Trabalho/UNESP/IC/Pesquisa2023')
library(urca)
library(lmtest)
library(sandwich)
library(mFilter)
library(tstools)
```

```{r}
dados <- read_excel("C:/Users/anafe/OneDrive/Área de Trabalho/UNESP/IC/Pesquisa2023/dados_uso.xlsx")
dados<-dados[,c('pib', 'coef_abertura', 'ipca', 'ipca_aliemntos', 'icbragro', 'ipa_agro', 'petroleo', 'e', 'indicefmi')]
dados_ts<- as.ts(dados, start = c(1999, 1), end = c(2023, 4), frequency = 12)
pib <- log(dados[,c('pib')])
pibhp<-hpfilter(pib,freq=12,type=c("frequency"),drift=FALSE)
pibciclo <- pibhp$cycle
ciclodf<-as.data.frame(pibciclo)
dados['pibciclo'] <- ciclodf
dados_ts2 <-as.ts(dados, start = c(1999, 1), end = c(2023, 4), frequency = 12)
dados_ts2[, 'coef_abertura'] = log(dados_ts2[, 'coef_abertura'])
dados_ts2[, 'ipca'] = log(dados_ts2[, 'ipca'])
dados_ts2[, 'icbragro'] = log(dados_ts2[, 'icbragro'])
dados_ts2[, 'ipa_agro'] = log(dados_ts2[, 'ipa_agro'])
dados_ts2[, 'petroleo'] = log(dados_ts2[, 'petroleo'])
dados_ts2[, 'e'] = log(dados_ts2[, 'e'])
dados_ts2[, 'indicefmi'] = log(dados_ts2[, 'indicefmi'])
dados_ts2 <- dados_ts2[,c('coef_abertura', 'ipca', 'ipca_aliemntos', 'icbragro', 'ipa_agro', 'petroleo', 'e', 'indicefmi', 'pibciclo')]
ipca <- dados_ts2[, 'ipca']
ipca <- diff(ipca)
ipcavar<-as.data.frame(ipca)
dados_ts2 = dados_ts2[- 1, ]
dados_ts2 <- cbind(ipcavar, dados_ts2)
colnames(dados_ts2)[colnames(dados_ts2)=='x']<-'ipcavar'
dados_ts2 <- dados_ts2[,c('coef_abertura', 'ipca_aliemntos', 'icbragro', 'ipa_agro', 'petroleo', 'e', 'indicefmi', 'pibciclo', 'ipcavar')]
dados2_ts<- as.ts(dados_ts2, start = c(1999, 2), end = c(2023, 4), frequency = 12)
```

```{r}
#Equação IPCA
dadosIPCA <- dados2_ts[,c('ipcavar', 'coef_abertura','indicefmi', 'petroleo', 'e', 'icbragro', 'pibciclo')]
dadosIPCA_ts <- as.ts(dadosIPCA, start = c(1999, 2), end = c(2023, 4), frequency = 12)
#Equação IPCA alimentos
dadosAlimentos <- dados2_ts[,c('ipca_aliemntos', 'coef_abertura', 'indicefmi', 'petroleo', 'e','icbragro', 'pibciclo')]
dadosAlimentos_ts <- as.ts(dadosAlimentos, start = c(1999, 2), end = c(2023, 4), frequency = 12)
#Equação IPA agrícola
dadosIPA <- dados2_ts[,c('ipa_agro','coef_abertura', 'indicefmi', 'petroleo','e', 'icbragro', 'pibciclo')]
dadosIPA_ts <- as.ts(dadosIPA, start = c(1999, 2), end = c(2023, 4), frequency = 12)
```

```{r}
#Teste de cointegração
#Traço
coint_tr <- ca.jo(dadosIPCA_ts, type = 'trace', ecdet = 'const', K = 5, spec="longrun")
#Traço Alimentos
coint_tr2 <- ca.jo(dadosAlimentos_ts, type = 'trace', ecdet = 'const', K = 5, spec="longrun")
#Traço
coint_tr3 <- ca.jo(dadosIPA_ts, type = 'trace', ecdet = 'const', K = 5, spec="longrun")
#Autovalor máximo
coint_ei <- ca.jo(dadosIPCA_ts, type = 'eigen', ecdet = 'const', K = 5, spec="longrun")
#Autovalor máximo
coint_ei2 <- ca.jo(dadosAlimentos_ts, type = 'eigen', ecdet = 'const', K = 5, spec="longrun")
#Autovalor máximo
coint_ei3 <- ca.jo(dadosIPA_ts, type = 'eigen', ecdet = 'const', K = 5, spec="longrun")
```

```{r}
#dadosIPCA
vecm1<- coint_tr
class(vecm1)
vecm.r1<- cajorls(vecm1, r=1)
#dadosAlimentos
vecm2<- coint_tr2
class(vecm2)
vecm.r2<- cajorls(vecm2, r=1)
#dadosIPA
vecm3<- coint_tr3
class(vecm3)
vecm.r3<- cajorls(vecm3, r=1)
```

```{r}
#RepresentaçãoVAR
VAR1<- vec2var(vecm1, r=1)
VAR2<- vec2var(vecm2, r=1)
VAR3<- vec2var(vecm3, r=1)
```

```{r}
#Função Impulso-resposta
IRF1 <- irf(VAR1,impulse = c('e'), n.ahead = 12, boot = TRUE)
IRF2 <- irf(VAR2,impulse = c('e'), n.ahead = 12, boot = TRUE)
IRF3 <- irf(VAR3,impulse = c('e'), n.ahead = 12, boot = TRUE)


```

```{r}
#DUMMY TEMPORAL IPCA
d2020 <- create_dummy_ts(end_basic = c(2023,4), dummy_start = c(2020,1), dummy_end = c(2021,12), start_basic = c(1999,2), frequency = 12)
d2020 <- ts(d2020)
dadosIPCA_DUMMY <- cbind(dadosIPCA_ts, d2020)
dadosAlimentos_DUMMY <- cbind(dadosAlimentos_ts, d2020)
dadosIPA_DUMMY <- cbind(dadosIPA_ts, d2020)
```

```{r}
#Teste de cointegração
#Traço
coint_trDUMMY <- ca.jo(dadosIPCA_DUMMY, type = 'trace', ecdet = 'const', K = 5, spec="longrun")
#Traço Alimentos
coint_tr2DUMMY <- ca.jo(dadosAlimentos_DUMMY, type = 'trace', ecdet = 'const', K = 5, spec="longrun")
#Traço
coint_tr3DUMMY <- ca.jo(dadosIPA_DUMMY, type = 'trace', ecdet = 'const', K = 5, spec="longrun")
#Autovalor máximo
coint_ei_DUMMY <- ca.jo(dadosIPCA_DUMMY, type = 'eigen', ecdet = 'const', K = 5, spec="longrun")
#Autovalor máximo
coint_ei2_DUMMY <- ca.jo(dadosAlimentos_DUMMY, type = 'eigen', ecdet = 'const', K = 5, spec="longrun")
#Autovalor máximo
coint_ei3_DUMMY <- ca.jo(dadosIPA_DUMMY, type = 'eigen', ecdet = 'const', K = 5, spec="longrun")
```

```{r}
#dadosIPCADUMMY
vecm1DUMMY<- coint_trDUMMY
vecm.r1DUMMY<- cajorls(vecm1DUMMY, r=1)
#dadosAlimentosDUMMY
vecm2DUMMY<- coint_tr2DUMMY
vecm.r2DUMMY<- cajorls(vecm2DUMMY, r=1)
#dadosIPA
vecm3DUMMY<- coint_tr3DUMMY
vecm.r3DUMMY<- cajorls(vecm3DUMMY, r=1)
```

```{r}
#RepresentaçãoVAR
VAR1DUMMY<- vec2var(vecm1DUMMY, r=1)
VAR2DUMMY<- vec2var(vecm2DUMMY, r=1)
VAR3DUMMY<- vec2var(vecm3DUMMY, r=1)
```

```{r}
#Função Impulso-resposta
IRF1DUMMY <- irf(VAR1DUMMY, impulse = c('dadosIPCA_ts.e'), n.ahead = 12, boot = TRUE)
IRF2DUMMY <- irf(VAR2DUMMY,impulse = c('dadosAlimentos_ts.e'), n.ahead = 12, boot = TRUE)
IRF3DUMMY <- irf(VAR3DUMMY,impulse = c('dadosIPA_ts.e'), n.ahead = 12, boot = TRUE)
```

```{r}
print(IRF1DUMMY)
```
```{r}
print(IRF2DUMMY)
```
```{r}
print(IRF3DUMMY)
```

```{r}
print(VAR3DUMMY)
```

